#!/bin/bash -ex

TESTED_HOST="${TESTED_HOST:-$(/bin/hostname)}"
INFLUXDB_HOST="${INFLUXDB_HOST:-http://localhost}"
INFLUXDB_PORT="${INFLUXDB_PORT:-8086}"
INFLUXDB_DB="${INFLUXDB_DB:-speedtests}"
INTERVAL_SECONDS="${INTERVAL_SECONDS:-300}"
OFFSET_SECONDS="${OFFSET_SECONDS:-$(($RANDOM % 300))}"

speedtest_args="--json --secure"

if [ -n "$SPEEDTEST_SERVER_ID" ]; then
    speedtest_args="${speedtest_args} --server=$SPEEDTEST_SERVER_ID"
fi

/bin/sleep $OFFSET_SECONDS

while true; do
    start_time="$(date +%s)"

    /usr/local/bin/speedtest ${speedtest_args} \
    | /usr/bin/jq \
        --raw-output \
        --arg host ${TESTED_HOST} \
        '"speedtests,host=\($host),speedtest_server_id=\(.server.id) download=\(.download),upload=\(.upload),ping=\(.ping) \(.timestamp | capture("(?<datetime>[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}).[0-9]{6}Z") | "\(.datetime | strptime("%Y-%m-%dT%H:%M:%S") | mktime)")"' \
    | /usr/bin/curl \
        --silent \
        --show-error \
        --request POST \
        --data-binary @- \
        "${INFLUXDB_HOST}:${INFLUXDB_PORT}/write?db=${INFLUXDB_DB}&precision=s"

    end_time=$(date +%s)
    elapsed_seconds=$(($end_time - $start_time))

    /bin/sleep $(($INTERVAL_SECONDS - $elapsed_seconds))
done 
